version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ci
      include: scope
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      aws-dependencies:
        patterns:
          - "aws-sdk-*"
          - "aws-config"
          - "aws-types"
    commit-message:
      prefix: chore
      prefix-development: test
      include: scope
