indent_style = "Block"
reorder_imports = true
merge_derives = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true # tracking issue https://github.com/rust-lang/rustfmt/issues/3348
