name: Bug report
description: Create a bug report to let us fix it
labels: bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Describe the bug.
      placeholder: >
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: >
        Steps to reproduce the behavior.
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: >
        What you expected to happen.